-- DRZAVA PODACI
INSERT ALL
   INTO DRZAVA (DRZ_ID, DRZ_NAZ) VALUES ('SRB', 'Srbija')
   INTO DRZAVA (DRZ_ID, DRZ_NAZ) VALUES ('ENG', 'Engleska')
   INTO DRZAVA (DRZ_ID, DRZ_NAZ) VALUES ('USA', 'Sjedinjene Americke Drzave')
   INTO DRZAVA (DRZ_ID, DRZ_NAZ) VALUES ('RUS', 'Rusija')
SELECT 1 FROM DUAL;

-- GRAD PODACI
INSERT ALL
   INTO GRAD (LOK_ID, LOK_NAZ, DRZ_ID) VALUES ('B?', 'Becej', 'SRB')
   INTO GRAD (LOK_ID, LOK_NAZ, DRZ_ID) VALUES ('BG', 'Beograd', 'SRB')
   INTO GRAD (LOK_ID, LOK_NAZ, DRZ_ID) VALUES ('NI', 'Nis', 'SRB')
   INTO GRAD (LOK_ID, LOK_NAZ, DRZ_ID) VALUES ('NS', 'Novi Sad', 'SRB')
SELECT 1 FROM DUAL;

-- ULICA PODACI
INSERT ALL
   INTO ULICA (ULICA_ID, ULICA_NAZ, LOK_ID, DRZ_ID) VALUES ('1', 'Novosadska', 'BC', 'SRB')
   INTO ULICA (ULICA_ID, ULICA_NAZ, LOK_ID, DRZ_ID) VALUES ('2', 'Uro?a predica', 'BC', 'SRB')
   INTO ULICA (ULICA_ID, ULICA_NAZ, LOK_ID, DRZ_ID) VALUES ('3', 'Jovana Jovanovica Zmaja', 'BC', 'SRB')
   INTO ULICA (ULICA_ID, ULICA_NAZ, LOK_ID, DRZ_ID) VALUES ('4', 'Zelena', 'BC', 'SRB')
SELECT 1 FROM DUAL;

-- ADRESA PODACI
INSERT ALL
   INTO ADRESA (ADRS_ID, ADRS_ULBR, ULICA_ID, LOK_ID, DRZ_ID) VALUES ('1', '26', '1', 'BC', 'SRB')
   INTO ADRESA (ADRS_ID, ADRS_ULBR, ULICA_ID, LOK_ID, DRZ_ID) VALUES ('2', 'BB', '1', 'BC', 'SRB')
   INTO ADRESA (ADRS_ID, ADRS_ULBR, ULICA_ID, LOK_ID, DRZ_ID) VALUES ('3', '102A', '2', 'BC', 'SRB')
   INTO ADRESA (ADRS_ID, ADRS_ULBR, ULICA_ID, LOK_ID, DRZ_ID) VALUES ('4', '1', '3', 'BC', 'SRB')
   INTO ADRESA (ADRS_ID, ADRS_ULBR, ULICA_ID, LOK_ID, DRZ_ID) VALUES ('5', '56', '1', 'BC', 'SRB')
   INTO ADRESA (ADRS_ID, ADRS_ULBR, ULICA_ID, LOK_ID, DRZ_ID) VALUES ('6', '33', '2', 'BC', 'SRB')
   INTO ADRESA (ADRS_ID, ADRS_ULBR, ULICA_ID, LOK_ID, DRZ_ID) VALUES ('7', '1C', '3', 'BC', 'SRB')
SELECT 1 FROM DUAL;

-- STRU?NA SPREMA PODACI
INSERT ALL
   INTO STRUCNA_SPREMA (STRUC_SPREM_ID, STRUC_SPREM_NAZ) VALUES ('V?S', 'Visa strucna sprema')
   INTO STRUCNA_SPREMA (STRUC_SPREM_ID, STRUC_SPREM_NAZ) VALUES ('VSS', 'Visoka strucna sprema')
   INTO STRUCNA_SPREMA (STRUC_SPREM_ID, STRUC_SPREM_NAZ) VALUES ('SPC', 'Specijalista')
   INTO STRUCNA_SPREMA (STRUC_SPREM_ID, STRUC_SPREM_NAZ) VALUES ('MAG', 'Magistratura')
   INTO STRUCNA_SPREMA (STRUC_SPREM_ID, STRUC_SPREM_NAZ) VALUES ('DOK', 'Doktorat')
SELECT 1 FROM DUAL;

-- STRU?NI ISPIT PODACI
INSERT ALL
   INTO STRUCNI_ISPIT (STR_ISP_OZN, STR_ISP_DAT_POL, STR_ISP_DAT_PREST) VALUES ('1234567', '12-FEB-2012', null)
   INTO STRUCNI_ISPIT (STR_ISP_OZN, STR_ISP_DAT_POL, STR_ISP_DAT_PREST) VALUES ('1234568', '15-APR-2011', '16-JUN-2016')
   INTO STRUCNI_ISPIT (STR_ISP_OZN, STR_ISP_DAT_POL, STR_ISP_DAT_PREST) VALUES ('1234569', '17-MAR-2013', null)
   INTO STRUCNI_ISPIT (STR_ISP_OZN, STR_ISP_DAT_POL, STR_ISP_DAT_PREST) VALUES ('1234501', '09-DEC-2018', null)
SELECT 1 FROM DUAL;

-- AGENT PODACI
INSERT ALL
   INTO AGENT (AGENT_ID, AGENT_IME, AGENT_PREZ, AGENT_TEL, STRUC_SPREM_ID, DRZ_DRZ_ID,AGENT_BRLK, ADRS_ID, ULICA_ID, LOK_ID, DRZ_ID, STR_ISP_OZN ) VALUES ('1', 'Petar', 'Petrovic', '021/ 691-3-458', 'V?S', 'SRB', '123456759', '1', '1', 'B?', 'SRB', '1234567')
   INTO AGENT (AGENT_ID, AGENT_IME, AGENT_PREZ, AGENT_TEL, STRUC_SPREM_ID, DRZ_DRZ_ID,AGENT_BRLK, ADRS_ID, ULICA_ID, LOK_ID, DRZ_ID, STR_ISP_OZN ) VALUES ('2', 'Marko', 'Markovic', '021/ 691-6-338', 'VSS', 'SRB', '123456769', '2', '1', 'B?', 'SRB', '1234568')
   INTO AGENT (AGENT_ID, AGENT_IME, AGENT_PREZ, AGENT_TEL, STRUC_SPREM_ID, DRZ_DRZ_ID,AGENT_BRLK, ADRS_ID, ULICA_ID, LOK_ID, DRZ_ID, STR_ISP_OZN ) VALUES ('3', 'Janko', 'Jankovic', '021/ 691-5-555', 'VSS', 'SRB', '123456779', '3', '2', 'B?', 'SRB', '1234569')
   INTO AGENT (AGENT_ID, AGENT_IME, AGENT_PREZ, AGENT_TEL, STRUC_SPREM_ID, DRZ_DRZ_ID,AGENT_BRLK, ADRS_ID, ULICA_ID, LOK_ID, DRZ_ID, STR_ISP_OZN ) VALUES ('4', 'Laza', 'Lazarevic', '021/ 691-1-123', 'VSS', 'SRB', '123456789', '4', '3', 'B?', 'SRB', '1234501')
SELECT 1 FROM DUAL;

-- TIP NEPOKRETNOSTI PODACI
INSERT ALL
   INTO TIP_NEPOKRETNOSTI (NEK_TIP_ID, NEK_TIP_NAZ) VALUES ('ST', 'stan')
   INTO TIP_NEPOKRETNOSTI (NEK_TIP_ID, NEK_TIP_NAZ) VALUES ('KU', 'kuca')
   INTO TIP_NEPOKRETNOSTI (NEK_TIP_ID, NEK_TIP_NAZ) VALUES ('DS', 'dvorisni stan')
   INTO TIP_NEPOKRETNOSTI (NEK_TIP_ID, NEK_TIP_NAZ) VALUES ('LK', 'lokal')
   INTO TIP_NEPOKRETNOSTI (NEK_TIP_ID, NEK_TIP_NAZ) VALUES ('PL', 'plac')
SELECT 1 FROM DUAL;

-- TIP POMO?NOG OBJEKTA PODACI
INSERT ALL
   INTO TIP_POMOCNOG_OBJEKTA (POM_OBJ_TIP_ID, POM_OBJ_TIP_NAZ) VALUES ('SU', 'supa')
   INTO TIP_POMOCNOG_OBJEKTA (POM_OBJ_TIP_ID, POM_OBJ_TIP_NAZ) VALUES ('ST', 'stala')
   INTO TIP_POMOCNOG_OBJEKTA (POM_OBJ_TIP_ID, POM_OBJ_TIP_NAZ) VALUES ('GA', 'garaza')
   INTO TIP_POMOCNOG_OBJEKTA (POM_OBJ_TIP_ID, POM_OBJ_TIP_NAZ) VALUES ('LK', 'letnja kuhinja')
SELECT 1 FROM DUAL;

-- PRIKLJU?AK PODACI
INSERT ALL
   INTO PRIKLJUCAK (PRIK_ID, PRIK_NAZ) VALUES ('1', 'struja')
   INTO PRIKLJUCAK (PRIK_ID, PRIK_NAZ) VALUES ('2', 'voda')
   INTO PRIKLJUCAK (PRIK_ID, PRIK_NAZ) VALUES ('3', 'gas')
   INTO PRIKLJUCAK (PRIK_ID, PRIK_NAZ) VALUES ('4', 'centralno grejanje')
SELECT 1 FROM DUAL;

-- ISHOD POSREDOVANJA PODACI
INSERT ALL
   INTO ISHOD_POSREDOVANJA (ISHOD_ID, ISHOD_NAZ) VALUES ('U', 'u toku')
   INTO ISHOD_POSREDOVANJA (ISHOD_ID, ISHOD_NAZ) VALUES ('P', 'prodato')
   INTO ISHOD_POSREDOVANJA (ISHOD_ID, ISHOD_NAZ) VALUES ('O', 'odustali')
   INTO ISHOD_POSREDOVANJA (ISHOD_ID, ISHOD_NAZ) VALUES ('I', 'isteklo')
SELECT 1 FROM DUAL;

-- KUPAC PODACI
INSERT ALL
   INTO KUPAC (KUP_ID, KUP_IME,KUP_PREZ, KUP_BRLK, KUP_TEL, KUP_EMAIL, ADRS_ID, ULICA_ID, LOK_ID, DRZ_ID ) VALUES ('1', 'Stanko', 'Petrovic','123456759', '021/ 691-3-458', null,  '1', '1', 'BC', 'SRB')
   INTO KUPAC (KUP_ID, KUP_IME,KUP_PREZ, KUP_BRLK, KUP_TEL, KUP_EMAIL, ADRS_ID, ULICA_ID, LOK_ID, DRZ_ID ) VALUES ('2', 'Milo?', 'Markovic','123456758', '021/ 691-6-338',  null,'2', '1', 'BC', 'SRB')
   INTO KUPAC (KUP_ID, KUP_IME,KUP_PREZ, KUP_BRLK, KUP_TEL, KUP_EMAIL, ADRS_ID, ULICA_ID, LOK_ID, DRZ_ID ) VALUES ('3', 'Ivan', 'JankoviC', '123456757','021/ 691-5-555',null, '3', '2', 'BC', 'SRB')
   INTO KUPAC (KUP_ID, KUP_IME,KUP_PREZ, KUP_BRLK, KUP_TEL, KUP_EMAIL, ADRS_ID, ULICA_ID, LOK_ID, DRZ_ID ) VALUES ('4', 'Bo?ko', 'Lazarevic', '123456756','021/ 691-1-123', null, '4', '3', 'BC', 'SRB')
SELECT 1 FROM DUAL;

-- PRODAVAC PODACI
INSERT ALL
   INTO PRODAVAC (PROD_ID, PROD_IME,PROD_PREZ, PROD_BRLK, PROD_TEL, PROD_EMAIL,PROD_ANONIM, ADRS_ID, ULICA_ID, LOK_ID, DRZ_ID ) VALUES ('1', 'Lepi', 'Lepic','987654321', '021/ 691-3-458', 'lepi@izaoblaka.com', '1', '1', '1', 'BC', 'SRB')
   INTO PRODAVAC (PROD_ID, PROD_IME,PROD_PREZ, PROD_BRLK, PROD_TEL, PROD_EMAIL,PROD_ANONIM, ADRS_ID, ULICA_ID, LOK_ID, DRZ_ID ) VALUES ('2', 'Nikola', 'Nikolic','987654321', '021/ 691-3-458', null, '2', '1', '1', 'BC', 'SRB')
   INTO PRODAVAC (PROD_ID, PROD_IME,PROD_PREZ, PROD_BRLK, PROD_TEL, PROD_EMAIL,PROD_ANONIM, ADRS_ID, ULICA_ID, LOK_ID, DRZ_ID ) VALUES ('3', 'Stefan', 'Stefanovic','987654321', '021/ 691-3-458', null, '3', '2', '1', 'BC', 'SRB')
SELECT 1 FROM DUAL;

-- NEPOKRETNOST PODACI
INSERT ALL
   INTO NEPOKRETNOST (NEK_ID, NEK_POV, NEK_USELJ, NEK_UIZGR, NEK_SOBE, NEK_SPRAT, NEK_DUPL,  NEK_LIFT, NEK_STARA, NEK_LEG, NEK_TAJNA, NEK_PROD, NEK_OPIS, NEK_TIP_ID, PROD_ID, ADRS_ID, ULICA_ID, LOK_ID, DRZ_ID, NEK_DAT_OD, NEK_DAT_DO) 
        VALUES ('1', '0000000200.00','1', '0', '5', '2', '0', '1','0','1','0','0','NEKI OPIS NEKRETNINE', 'ST', '1',  '1', '1', 'BC', 'SRB', '25-JAN-2016', null)
   INTO NEPOKRETNOST (NEK_ID, NEK_POV, NEK_USELJ, NEK_UIZGR, NEK_SOBE, NEK_SPRAT, NEK_DUPL,  NEK_LIFT, NEK_STARA, NEK_LEG, NEK_TAJNA, NEK_PROD, NEK_OPIS, NEK_TIP_ID, PROD_ID, ADRS_ID, ULICA_ID, LOK_ID, DRZ_ID, NEK_DAT_OD, NEK_DAT_DO) 
        VALUES ('1', '0000000100.00','1', '0', '3', '0', '0', '0','0','1','0','0','NEKI OPIS NEKRETNINE', 'KU', '2',  '2', '1', 'BC', 'SRB', '25-DEC-2015', null)
SELECT 1 FROM DUAL;

-- POMO?NI OBJEKAT PODACI
INSERT ALL
   INTO POMOCNI_OBJEKAT (POM_OBJ_ID,POM_OBJ_NAZ, POM_OBJ_POV, POM_OBJ_TIP_ID, NEK_ID, NEK_TIP_ID, PROD_ID) VALUES ('1', 'Stara supa', '0000000010.00','SU', '1', 'KU', '2' )
   INTO POMOCNI_OBJEKAT (POM_OBJ_ID,POM_OBJ_NAZ, POM_OBJ_POV, POM_OBJ_TIP_ID, NEK_ID, NEK_TIP_ID, PROD_ID) VALUES ('2', 'Garaza', '0000000018.00','GA', '1', 'KU', '2' )
   INTO POMOCNI_OBJEKAT (POM_OBJ_ID,POM_OBJ_NAZ, POM_OBJ_POV, POM_OBJ_TIP_ID, NEK_ID, NEK_TIP_ID, PROD_ID) VALUES ('3', 'Letnja kuhinjica', '000000008.00','LK', '1', 'KU', '2' )
   INTO POMOCNI_OBJEKAT (POM_OBJ_ID,POM_OBJ_NAZ, POM_OBJ_POV, POM_OBJ_TIP_ID, NEK_ID, NEK_TIP_ID, PROD_ID) VALUES ('1', 'Podzemna garaza', '0000000020.00','GA', '1', 'ST', '1' )
SELECT 1 FROM DUAL;

-- SLIKA PODACI
INSERT ALL
   INTO SLIKA (SLIKA_ID, SLIKA_NAZ, SLIKA_PUT, SLIKA_OPIS, NEK_ID, NEK_TIP_ID, POM_OBJ_ID, POM_OBJ_TIP_ID, PROD_ID) VALUES ('1', 'Slika objekta','http://nes.nes/nek/slika.jpg', 'Ovo je moja kuca.', '1', 'KU',null,null, '2' )
   INTO SLIKA (SLIKA_ID, SLIKA_NAZ, SLIKA_PUT, SLIKA_OPIS, NEK_ID, NEK_TIP_ID, POM_OBJ_ID, POM_OBJ_TIP_ID, PROD_ID) VALUES ('2', 'Slika pomocnog objekta','http://nes.nes/nek/slika.jpg', 'Ovo je moja supa.', null, null,'1','SU', null )
SELECT 1 FROM DUAL;

-- UGOVOR O POSREDOVANJU PODACI
INSERT ALL
   INTO UGOVOR_O_POSREDOVANJU(POSR_SVRHA, POSR_DAT_SKL, POSR_ROK, POSR_DAT_IST, POSR_ID,POSR_TROSK,POSR_OTK_ROK,POSR_NAZ_SUDA,POSR_TEL_SUDA,POSR_BRPR,POSR_BRPOSTR,POSR_POTP,AGENT_AGENT_ID,KUPAC_KUP_ID,ISHOD_ID,NEK_ID,NEK_TIP_ID,ADRS_ID,ULICA_ID,LOK_ID,DRZ_ID,PROD_ID)
      VALUES('Posredovanje u prodaji stana', '25-JAN-2016', '25-JAN-2017', '25-JAN-2017', '1', '0000000100.00', '09-FEB-2016', 'Prvi osnovni sud', '021/691-2-535', '4', '2', '1', '1', null, 'U', '1', 'ST', '1', '1', 'BC', 'SRB', '1')
   INTO UGOVOR_O_POSREDOVANJU(POSR_SVRHA, POSR_DAT_SKL, POSR_ROK, POSR_DAT_IST, POSR_ID,POSR_TROSK,POSR_OTK_ROK,POSR_NAZ_SUDA,POSR_TEL_SUDA,POSR_BRPR,POSR_BRPOSTR,POSR_POTP,AGENT_AGENT_ID,KUPAC_KUP_ID,ISHOD_ID,NEK_ID,NEK_TIP_ID,ADRS_ID,ULICA_ID,LOK_ID,DRZ_ID,PROD_ID)
      VALUES('Posredovanje u prodaji kuce', '25-DEC-2015', '25-DEC-2016', '25-DEC-2016', '2', '0000000050.00', '09-JAN-2015', 'Prvi osnovni sud', '021/691-2-535', '4', '2', '1', '1', '1', 'P', '1', 'KU', '1', '1', 'BC', 'SRB', '2')
SELECT 1 FROM DUAL;


